### ISSUE TITLE
Reshade and RT64

### ISSUE THREAD

**Issue by HHasashi** [DarioSamo/sm64rt#20]
I installed Reshade 4.90 and it seems to not work, so I wondered if it is possible to use Reshade with Mario RT64 ?
I'd like to use Reshade to implement MXAO and some color correction btw.
I chose DX10/11/12 as the API used for the game too.

Sorry if the issue is not clear or lacks information.

**Comment by DarioSamo** [comment]
Reshade will most likely not work as there's zero rasterization being done that it could rely on.

**Comment by HHasashi** [comment]
Okok I see, will it ever be a Reshade compatible ?

**Comment by DarioSamo** [comment]
I don't think so, because it means it'd need to be a rasterizer (or maybe it just needs a fake depth buffer, I don't know what Reshade hooks into).

**Comment by HHasashi** [comment]
For MXAO, depth buffer suffice, for color correction, it's just a filter.
Reshade and MXAO works well with other SM64 builds such as Render96, there's no problem so far.
But the Reshader doesn't seem to even load when playing RT64, and at the installation it doesn't detect which API is used.

**Comment by jrouzies-fr** [comment]
Hey Dario, why would it be closed?

Reshade is saying there is No depth buffer available for this version. 

It would be really interesting to be able to inject some Ambient Occlusion, unless you could implement ray traced AO directly?

Thanks

**Comment by DarioSamo** [comment]
It's closed because it's not something I can really solve. Reshade looks for the depth buffer used by a rasterization process. It won't find it in a path tracer. I can't really offer it the same way to hook into it unless I basically render the entire scene in raster.

Besides, AO is already in the form of GI already, it's just not as pronounced as adding fake darkness, but it's definitely working as intended.
